// ./layout.tsx 布局组件，多个页面共享布局共享ui组件 
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import rootLayout from "@/components/layout/root";
import Home from "./page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(children) {
  return (
    <html lang="en">
      <body>
        {rootLayout(children)}
      </body>
    </html>
  );
}
